name: cat_facts
description: App that gets cat facts.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
